# Generated by Django 5.0.3 on 2024-04-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculation',
            options={'verbose_name': 'Обрахунок', 'verbose_name_plural': 'Обрахунки'},
        ),
        migrations.AddField(
            model_name='calculation',
            name='city',
            field=models.CharField(default='Рівне', max_length=250, verbose_name='Місто'),
        ),
    ]
